<?php

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_5e46a6210a31d',
	'title' => 'Dashboard',
	'fields' => array(
		array(
			'key' => 'field_5e46a62119242',
			'label' => 'Hide Dashboard Items',
			'name' => 'typemarker_dashboard_hide',
			'type' => 'checkbox',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Tooltips' => 'Tooltips',
				'Screen Options' => 'Screen Options',
				'Documentation' => 'Documentation',
				'Account' => 'Account',
				'Posts' => 'Posts',
				'Pages' => 'Pages',
				'Users' => 'Users',
				'Settings' => 'Settings',
				'Status' => 'Status',
				'Logo' => 'Logo',
			),
			'allow_custom' => 0,
			'default_value' => array(
			),
			'layout' => 'vertical',
			'toggle' => 1,
			'return_format' => 'value',
			'save_custom' => 0,
		),
		array(
			'key' => 'field_5e46a6210c86e',
			'label' => 'Theme Colors',
			'name' => 'typemarker_dashboard_color_theme',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5e46a6210e1cd',
					'label' => 'Primary',
					'name' => 'primary',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#7fb100',
				),
				array(
					'key' => 'field_5e46a6210e1e5',
					'label' => 'Secondary',
					'name' => 'secondary',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#e0e1e2',
				),
				array(
					'key' => 'field_5e46a6210e1ea',
					'label' => 'Base',
					'name' => 'base',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#1c1d1b',
				),
			),
		),
		array(
			'key' => 'field_5e46a62111004',
			'label' => 'Accent Colors',
			'name' => 'typemarker_dashboard_color_accent',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5e46a62111c1c',
					'label' => 'Good',
					'name' => 'good',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#7fb100',
				),
				array(
					'key' => 'field_5e46a62111c22',
					'label' => 'Attention',
					'name' => 'attention',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#fbbd08',
				),
				array(
					'key' => 'field_5e46a62111c27',
					'label' => 'Critical',
					'name' => 'critical',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#a00000',
				),
			),
		),
		array(
			'key' => 'field_5e46a621155ed',
			'label' => 'Grayscale Colors',
			'name' => 'typemarker_dashboard_color_grayscale',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5e46a62116473',
					'label' => 'Pseudo Black',
					'name' => 'black_pseudo',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#070707',
				),
				array(
					'key' => 'field_5e46a6211647a',
					'label' => 'Gray',
					'name' => 'gray',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#aeaea8',
				),
				array(
					'key' => 'field_5e46a6211647f',
					'label' => 'Pseudo White',
					'name' => 'white_pseudo',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#fafafa',
				),
			),
		),
		array(
			'key' => 'field_5e46a62114b13',
			'label' => 'Dashboard Logo',
			'name' => 'typemarker_dashboard_logo',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'id',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => 'jpg,jpeg,png',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'typemarker',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5e46a627913af',
	'title' => 'Pro Reports',
	'fields' => array(
		array(
			'key' => 'field_5e46a627a22f2',
			'label' => 'Pro Report Templates',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '44',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
		),
		array(
			'key' => 'field_5e50394deaf62',
			'label' => 'Document Size',
			'name' => 'typemarker_reports_pdf_paper_format',
			'type' => 'button_group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '14',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'a4' => 'A4 (210 x 297mm)',
				'letter' => 'Letter (8.5 x 11in)',
			),
			'allow_null' => 0,
			'default_value' => 'a4',
			'layout' => 'vertical',
			'return_format' => 'value',
		),
		array(
			'key' => 'field_5e509a65d93f3',
			'label' => 'Document Orientation',
			'name' => 'typemarker_reports_pdf_paper_orientation',
			'type' => 'button_group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '14',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'portrait' => 'Portrait',
				'landscape' => 'Landscape',
			),
			'allow_null' => 0,
			'default_value' => 'portrait',
			'layout' => 'vertical',
			'return_format' => 'value',
		),
		array(
			'key' => 'field_5e61b2562ca0e',
			'label' => 'Analytics',
			'name' => 'typemarker_reports_analytics',
			'type' => 'button_group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '14',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'google' => 'Google Analytics',
				'matomo' => 'Matomo',
			),
			'allow_null' => 0,
			'default_value' => 'a4',
			'layout' => 'vertical',
			'return_format' => 'value',
		),
		array(
			'key' => 'field_5e61b2b62ca0f',
			'label' => 'Security',
			'name' => 'typemarker_reports_security',
			'type' => 'button_group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '14',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'sucuri' => 'Sucuri',
				'wordfence' => 'Wordfence',
			),
			'allow_null' => 0,
			'default_value' => 'sucuri',
			'layout' => 'vertical',
			'return_format' => 'value',
		),
		array(
			'key' => 'field_5e46a627a4736',
			'label' => 'Use Colors',
			'name' => 'typemarker_reports_color_scheme',
			'type' => 'button_group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'report' => 'Report',
				'dashboard' => 'MainWP Dashboard',
				'client' => 'Client Tokens',
			),
			'allow_null' => 0,
			'default_value' => 'report',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array(
			'key' => 'field_5e46a627a473a',
			'label' => 'Default Client Color',
			'name' => 'typemarker_reports_color_token_client_brand_color_primary_default',
			'type' => 'color_picker',
			'instructions' => 'This will be used if [client.brand.color.primary] is not set for a site.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '35',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#296a7f',
		),
		array(
			'key' => 'field_5e46a627a473f',
			'label' => 'Default Client Accent',
			'name' => 'typemarker_reports_color_token_client_brand_color_accent_default',
			'type' => 'color_picker',
			'instructions' => 'This will be used if [client.brand.color.accent] is not set for a site.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '35',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#d3ac58',
		),
		array(
			'key' => 'field_5e46a97b1e9f2',
			'label' => 'Call to Action',
			'name' => 'typemarker_reports_cta',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5e46a9a51e9f3',
					'label' => 'CTA Button Text',
					'name' => 'text',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '40',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5e46a9fc1e9f4',
					'label' => 'Link URL',
					'name' => 'url',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '60',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
			),
		),
		array(
			'key' => 'field_5e6691e21f3b1',
			'label' => 'Email Images',
			'name' => 'typemarker_reports_email_images_as',
			'type' => 'button_group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '17',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'data' => 'Data URI',
				'external' => 'External URL',
			),
			'allow_null' => 0,
			'default_value' => '',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array(
			'key' => 'field_5e566d6a8dbb7',
			'label' => 'Email Image',
			'name' => 'typemarker_reports_email_image',
			'type' => 'button_group',
			'instructions' => 'Featured as header in email message.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'none' => 'None',
				'header_image' => 'Header Image',
				'logo' => 'Logo',
			),
			'allow_null' => 0,
			'default_value' => 'none',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array(
			'key' => 'field_5e46a627a2e19',
			'label' => 'Agency URL',
			'name' => 'typemarker_reports_business_url',
			'type' => 'url',
			'instructions' => 'Used to hyperlink your logo in most templates.',
			'required' => 1,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5e46a627a4736',
						'operator' => '!=empty',
					),
				),
			),
			'wrapper' => array(
				'width' => '23',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5e5440db0ea45',
			'label' => 'Footer Text',
			'name' => 'typemarker_reports_footer_text',
			'type' => 'text',
			'instructions' => 'This will be used in the footer of both email and PDF.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '40',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'typemarker',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

endif;
